/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    AvatarGroup: typeof import('primevue/avatargroup')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Editor: typeof import('primevue/editor')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    PickList: typeof import('primevue/picklist')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    Step: typeof import('primevue/step')['default']
    StepItem: typeof import('primevue/stepitem')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
